// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// OauthUserInfo is an object representing the database table.
type OauthUserInfo struct {
	ID                    string    `boil:"id" json:"id" toml:"id" yaml:"id"`
	UserID                string    `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	ProviderID            string    `boil:"provider_id" json:"provider_id" toml:"provider_id" yaml:"provider_id"`
	ProviderUID           string    `boil:"provider_uid" json:"provider_uid" toml:"provider_uid" yaml:"provider_uid"`
	AccessToken           string    `boil:"access_token" json:"access_token" toml:"access_token" yaml:"access_token"`
	RefreshToken          string    `boil:"refresh_token" json:"refresh_token" toml:"refresh_token" yaml:"refresh_token"`
	AccessTokenExpiresAt  time.Time `boil:"access_token_expires_at" json:"access_token_expires_at" toml:"access_token_expires_at" yaml:"access_token_expires_at"`
	RefreshTokenExpiresAt null.Time `boil:"refresh_token_expires_at" json:"refresh_token_expires_at,omitempty" toml:"refresh_token_expires_at" yaml:"refresh_token_expires_at,omitempty"`
	CreatedAt             time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt             time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *oauthUserInfoR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L oauthUserInfoL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var OauthUserInfoColumns = struct {
	ID                    string
	UserID                string
	ProviderID            string
	ProviderUID           string
	AccessToken           string
	RefreshToken          string
	AccessTokenExpiresAt  string
	RefreshTokenExpiresAt string
	CreatedAt             string
	UpdatedAt             string
}{
	ID:                    "id",
	UserID:                "user_id",
	ProviderID:            "provider_id",
	ProviderUID:           "provider_uid",
	AccessToken:           "access_token",
	RefreshToken:          "refresh_token",
	AccessTokenExpiresAt:  "access_token_expires_at",
	RefreshTokenExpiresAt: "refresh_token_expires_at",
	CreatedAt:             "created_at",
	UpdatedAt:             "updated_at",
}

var OauthUserInfoTableColumns = struct {
	ID                    string
	UserID                string
	ProviderID            string
	ProviderUID           string
	AccessToken           string
	RefreshToken          string
	AccessTokenExpiresAt  string
	RefreshTokenExpiresAt string
	CreatedAt             string
	UpdatedAt             string
}{
	ID:                    "oauth_user_info.id",
	UserID:                "oauth_user_info.user_id",
	ProviderID:            "oauth_user_info.provider_id",
	ProviderUID:           "oauth_user_info.provider_uid",
	AccessToken:           "oauth_user_info.access_token",
	RefreshToken:          "oauth_user_info.refresh_token",
	AccessTokenExpiresAt:  "oauth_user_info.access_token_expires_at",
	RefreshTokenExpiresAt: "oauth_user_info.refresh_token_expires_at",
	CreatedAt:             "oauth_user_info.created_at",
	UpdatedAt:             "oauth_user_info.updated_at",
}

// Generated where

var OauthUserInfoWhere = struct {
	ID                    whereHelperstring
	UserID                whereHelperstring
	ProviderID            whereHelperstring
	ProviderUID           whereHelperstring
	AccessToken           whereHelperstring
	RefreshToken          whereHelperstring
	AccessTokenExpiresAt  whereHelpertime_Time
	RefreshTokenExpiresAt whereHelpernull_Time
	CreatedAt             whereHelpertime_Time
	UpdatedAt             whereHelpertime_Time
}{
	ID:                    whereHelperstring{field: "`oauth_user_info`.`id`"},
	UserID:                whereHelperstring{field: "`oauth_user_info`.`user_id`"},
	ProviderID:            whereHelperstring{field: "`oauth_user_info`.`provider_id`"},
	ProviderUID:           whereHelperstring{field: "`oauth_user_info`.`provider_uid`"},
	AccessToken:           whereHelperstring{field: "`oauth_user_info`.`access_token`"},
	RefreshToken:          whereHelperstring{field: "`oauth_user_info`.`refresh_token`"},
	AccessTokenExpiresAt:  whereHelpertime_Time{field: "`oauth_user_info`.`access_token_expires_at`"},
	RefreshTokenExpiresAt: whereHelpernull_Time{field: "`oauth_user_info`.`refresh_token_expires_at`"},
	CreatedAt:             whereHelpertime_Time{field: "`oauth_user_info`.`created_at`"},
	UpdatedAt:             whereHelpertime_Time{field: "`oauth_user_info`.`updated_at`"},
}

// OauthUserInfoRels is where relationship names are stored.
var OauthUserInfoRels = struct {
	Provider string
	User     string
}{
	Provider: "Provider",
	User:     "User",
}

// oauthUserInfoR is where relationships are stored.
type oauthUserInfoR struct {
	Provider *OauthProvider `boil:"Provider" json:"Provider" toml:"Provider" yaml:"Provider"`
	User     *User          `boil:"User" json:"User" toml:"User" yaml:"User"`
}

// NewStruct creates a new relationship struct
func (*oauthUserInfoR) NewStruct() *oauthUserInfoR {
	return &oauthUserInfoR{}
}

func (r *oauthUserInfoR) GetProvider() *OauthProvider {
	if r == nil {
		return nil
	}
	return r.Provider
}

func (r *oauthUserInfoR) GetUser() *User {
	if r == nil {
		return nil
	}
	return r.User
}

// oauthUserInfoL is where Load methods for each relationship are stored.
type oauthUserInfoL struct{}

var (
	oauthUserInfoAllColumns            = []string{"id", "user_id", "provider_id", "provider_uid", "access_token", "refresh_token", "access_token_expires_at", "refresh_token_expires_at", "created_at", "updated_at"}
	oauthUserInfoColumnsWithoutDefault = []string{"id", "user_id", "provider_id", "provider_uid", "access_token", "refresh_token", "access_token_expires_at", "refresh_token_expires_at"}
	oauthUserInfoColumnsWithDefault    = []string{"created_at", "updated_at"}
	oauthUserInfoPrimaryKeyColumns     = []string{"id"}
	oauthUserInfoGeneratedColumns      = []string{}
)

type (
	// OauthUserInfoSlice is an alias for a slice of pointers to OauthUserInfo.
	// This should almost always be used instead of []OauthUserInfo.
	OauthUserInfoSlice []*OauthUserInfo
	// OauthUserInfoHook is the signature for custom OauthUserInfo hook methods
	OauthUserInfoHook func(context.Context, boil.ContextExecutor, *OauthUserInfo) error

	oauthUserInfoQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	oauthUserInfoType                 = reflect.TypeOf(&OauthUserInfo{})
	oauthUserInfoMapping              = queries.MakeStructMapping(oauthUserInfoType)
	oauthUserInfoPrimaryKeyMapping, _ = queries.BindMapping(oauthUserInfoType, oauthUserInfoMapping, oauthUserInfoPrimaryKeyColumns)
	oauthUserInfoInsertCacheMut       sync.RWMutex
	oauthUserInfoInsertCache          = make(map[string]insertCache)
	oauthUserInfoUpdateCacheMut       sync.RWMutex
	oauthUserInfoUpdateCache          = make(map[string]updateCache)
	oauthUserInfoUpsertCacheMut       sync.RWMutex
	oauthUserInfoUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var oauthUserInfoAfterSelectHooks []OauthUserInfoHook

var oauthUserInfoBeforeInsertHooks []OauthUserInfoHook
var oauthUserInfoAfterInsertHooks []OauthUserInfoHook

var oauthUserInfoBeforeUpdateHooks []OauthUserInfoHook
var oauthUserInfoAfterUpdateHooks []OauthUserInfoHook

var oauthUserInfoBeforeDeleteHooks []OauthUserInfoHook
var oauthUserInfoAfterDeleteHooks []OauthUserInfoHook

var oauthUserInfoBeforeUpsertHooks []OauthUserInfoHook
var oauthUserInfoAfterUpsertHooks []OauthUserInfoHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *OauthUserInfo) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range oauthUserInfoAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *OauthUserInfo) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range oauthUserInfoBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *OauthUserInfo) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range oauthUserInfoAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *OauthUserInfo) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range oauthUserInfoBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *OauthUserInfo) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range oauthUserInfoAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *OauthUserInfo) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range oauthUserInfoBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *OauthUserInfo) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range oauthUserInfoAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *OauthUserInfo) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range oauthUserInfoBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *OauthUserInfo) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range oauthUserInfoAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddOauthUserInfoHook registers your hook function for all future operations.
func AddOauthUserInfoHook(hookPoint boil.HookPoint, oauthUserInfoHook OauthUserInfoHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		oauthUserInfoAfterSelectHooks = append(oauthUserInfoAfterSelectHooks, oauthUserInfoHook)
	case boil.BeforeInsertHook:
		oauthUserInfoBeforeInsertHooks = append(oauthUserInfoBeforeInsertHooks, oauthUserInfoHook)
	case boil.AfterInsertHook:
		oauthUserInfoAfterInsertHooks = append(oauthUserInfoAfterInsertHooks, oauthUserInfoHook)
	case boil.BeforeUpdateHook:
		oauthUserInfoBeforeUpdateHooks = append(oauthUserInfoBeforeUpdateHooks, oauthUserInfoHook)
	case boil.AfterUpdateHook:
		oauthUserInfoAfterUpdateHooks = append(oauthUserInfoAfterUpdateHooks, oauthUserInfoHook)
	case boil.BeforeDeleteHook:
		oauthUserInfoBeforeDeleteHooks = append(oauthUserInfoBeforeDeleteHooks, oauthUserInfoHook)
	case boil.AfterDeleteHook:
		oauthUserInfoAfterDeleteHooks = append(oauthUserInfoAfterDeleteHooks, oauthUserInfoHook)
	case boil.BeforeUpsertHook:
		oauthUserInfoBeforeUpsertHooks = append(oauthUserInfoBeforeUpsertHooks, oauthUserInfoHook)
	case boil.AfterUpsertHook:
		oauthUserInfoAfterUpsertHooks = append(oauthUserInfoAfterUpsertHooks, oauthUserInfoHook)
	}
}

// One returns a single oauthUserInfo record from the query.
func (q oauthUserInfoQuery) One(ctx context.Context, exec boil.ContextExecutor) (*OauthUserInfo, error) {
	o := &OauthUserInfo{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for oauth_user_info")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all OauthUserInfo records from the query.
func (q oauthUserInfoQuery) All(ctx context.Context, exec boil.ContextExecutor) (OauthUserInfoSlice, error) {
	var o []*OauthUserInfo

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to OauthUserInfo slice")
	}

	if len(oauthUserInfoAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all OauthUserInfo records in the query.
func (q oauthUserInfoQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count oauth_user_info rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q oauthUserInfoQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if oauth_user_info exists")
	}

	return count > 0, nil
}

// Provider pointed to by the foreign key.
func (o *OauthUserInfo) Provider(mods ...qm.QueryMod) oauthProviderQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`id` = ?", o.ProviderID),
	}

	queryMods = append(queryMods, mods...)

	return OauthProviders(queryMods...)
}

// User pointed to by the foreign key.
func (o *OauthUserInfo) User(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`id` = ?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// LoadProvider allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (oauthUserInfoL) LoadProvider(ctx context.Context, e boil.ContextExecutor, singular bool, maybeOauthUserInfo interface{}, mods queries.Applicator) error {
	var slice []*OauthUserInfo
	var object *OauthUserInfo

	if singular {
		var ok bool
		object, ok = maybeOauthUserInfo.(*OauthUserInfo)
		if !ok {
			object = new(OauthUserInfo)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeOauthUserInfo)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeOauthUserInfo))
			}
		}
	} else {
		s, ok := maybeOauthUserInfo.(*[]*OauthUserInfo)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeOauthUserInfo)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeOauthUserInfo))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &oauthUserInfoR{}
		}
		args = append(args, object.ProviderID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &oauthUserInfoR{}
			}

			for _, a := range args {
				if a == obj.ProviderID {
					continue Outer
				}
			}

			args = append(args, obj.ProviderID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`oauth_provider`),
		qm.WhereIn(`oauth_provider.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load OauthProvider")
	}

	var resultSlice []*OauthProvider
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice OauthProvider")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for oauth_provider")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for oauth_provider")
	}

	if len(oauthProviderAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Provider = foreign
		if foreign.R == nil {
			foreign.R = &oauthProviderR{}
		}
		foreign.R.ProviderOauthUserInfos = append(foreign.R.ProviderOauthUserInfos, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ProviderID == foreign.ID {
				local.R.Provider = foreign
				if foreign.R == nil {
					foreign.R = &oauthProviderR{}
				}
				foreign.R.ProviderOauthUserInfos = append(foreign.R.ProviderOauthUserInfos, local)
				break
			}
		}
	}

	return nil
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (oauthUserInfoL) LoadUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeOauthUserInfo interface{}, mods queries.Applicator) error {
	var slice []*OauthUserInfo
	var object *OauthUserInfo

	if singular {
		var ok bool
		object, ok = maybeOauthUserInfo.(*OauthUserInfo)
		if !ok {
			object = new(OauthUserInfo)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeOauthUserInfo)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeOauthUserInfo))
			}
		}
	} else {
		s, ok := maybeOauthUserInfo.(*[]*OauthUserInfo)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeOauthUserInfo)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeOauthUserInfo))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &oauthUserInfoR{}
		}
		args = append(args, object.UserID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &oauthUserInfoR{}
			}

			for _, a := range args {
				if a == obj.UserID {
					continue Outer
				}
			}

			args = append(args, obj.UserID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`user`),
		qm.WhereIn(`user.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for user")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for user")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.OauthUserInfos = append(foreign.R.OauthUserInfos, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserID == foreign.ID {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.OauthUserInfos = append(foreign.R.OauthUserInfos, local)
				break
			}
		}
	}

	return nil
}

// SetProvider of the oauthUserInfo to the related item.
// Sets o.R.Provider to related.
// Adds o to related.R.ProviderOauthUserInfos.
func (o *OauthUserInfo) SetProvider(ctx context.Context, exec boil.ContextExecutor, insert bool, related *OauthProvider) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `oauth_user_info` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"provider_id"}),
		strmangle.WhereClause("`", "`", 0, oauthUserInfoPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ProviderID = related.ID
	if o.R == nil {
		o.R = &oauthUserInfoR{
			Provider: related,
		}
	} else {
		o.R.Provider = related
	}

	if related.R == nil {
		related.R = &oauthProviderR{
			ProviderOauthUserInfos: OauthUserInfoSlice{o},
		}
	} else {
		related.R.ProviderOauthUserInfos = append(related.R.ProviderOauthUserInfos, o)
	}

	return nil
}

// SetUser of the oauthUserInfo to the related item.
// Sets o.R.User to related.
// Adds o to related.R.OauthUserInfos.
func (o *OauthUserInfo) SetUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `oauth_user_info` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"user_id"}),
		strmangle.WhereClause("`", "`", 0, oauthUserInfoPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserID = related.ID
	if o.R == nil {
		o.R = &oauthUserInfoR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			OauthUserInfos: OauthUserInfoSlice{o},
		}
	} else {
		related.R.OauthUserInfos = append(related.R.OauthUserInfos, o)
	}

	return nil
}

// OauthUserInfos retrieves all the records using an executor.
func OauthUserInfos(mods ...qm.QueryMod) oauthUserInfoQuery {
	mods = append(mods, qm.From("`oauth_user_info`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`oauth_user_info`.*"})
	}

	return oauthUserInfoQuery{q}
}

// FindOauthUserInfo retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindOauthUserInfo(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*OauthUserInfo, error) {
	oauthUserInfoObj := &OauthUserInfo{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `oauth_user_info` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, oauthUserInfoObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from oauth_user_info")
	}

	if err = oauthUserInfoObj.doAfterSelectHooks(ctx, exec); err != nil {
		return oauthUserInfoObj, err
	}

	return oauthUserInfoObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *OauthUserInfo) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no oauth_user_info provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(oauthUserInfoColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	oauthUserInfoInsertCacheMut.RLock()
	cache, cached := oauthUserInfoInsertCache[key]
	oauthUserInfoInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			oauthUserInfoAllColumns,
			oauthUserInfoColumnsWithDefault,
			oauthUserInfoColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(oauthUserInfoType, oauthUserInfoMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(oauthUserInfoType, oauthUserInfoMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `oauth_user_info` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `oauth_user_info` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `oauth_user_info` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, oauthUserInfoPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into oauth_user_info")
	}

	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for oauth_user_info")
	}

CacheNoHooks:
	if !cached {
		oauthUserInfoInsertCacheMut.Lock()
		oauthUserInfoInsertCache[key] = cache
		oauthUserInfoInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the OauthUserInfo.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *OauthUserInfo) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	oauthUserInfoUpdateCacheMut.RLock()
	cache, cached := oauthUserInfoUpdateCache[key]
	oauthUserInfoUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			oauthUserInfoAllColumns,
			oauthUserInfoPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update oauth_user_info, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `oauth_user_info` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, oauthUserInfoPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(oauthUserInfoType, oauthUserInfoMapping, append(wl, oauthUserInfoPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update oauth_user_info row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for oauth_user_info")
	}

	if !cached {
		oauthUserInfoUpdateCacheMut.Lock()
		oauthUserInfoUpdateCache[key] = cache
		oauthUserInfoUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q oauthUserInfoQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for oauth_user_info")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for oauth_user_info")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o OauthUserInfoSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), oauthUserInfoPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `oauth_user_info` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, oauthUserInfoPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in oauthUserInfo slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all oauthUserInfo")
	}
	return rowsAff, nil
}

var mySQLOauthUserInfoUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *OauthUserInfo) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no oauth_user_info provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(oauthUserInfoColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLOauthUserInfoUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	oauthUserInfoUpsertCacheMut.RLock()
	cache, cached := oauthUserInfoUpsertCache[key]
	oauthUserInfoUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			oauthUserInfoAllColumns,
			oauthUserInfoColumnsWithDefault,
			oauthUserInfoColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			oauthUserInfoAllColumns,
			oauthUserInfoPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("models: unable to upsert oauth_user_info, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "`oauth_user_info`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `oauth_user_info` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(oauthUserInfoType, oauthUserInfoMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(oauthUserInfoType, oauthUserInfoMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for oauth_user_info")
	}

	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(oauthUserInfoType, oauthUserInfoMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for oauth_user_info")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for oauth_user_info")
	}

CacheNoHooks:
	if !cached {
		oauthUserInfoUpsertCacheMut.Lock()
		oauthUserInfoUpsertCache[key] = cache
		oauthUserInfoUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single OauthUserInfo record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *OauthUserInfo) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no OauthUserInfo provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), oauthUserInfoPrimaryKeyMapping)
	sql := "DELETE FROM `oauth_user_info` WHERE `id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from oauth_user_info")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for oauth_user_info")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q oauthUserInfoQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no oauthUserInfoQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from oauth_user_info")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for oauth_user_info")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o OauthUserInfoSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(oauthUserInfoBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), oauthUserInfoPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `oauth_user_info` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, oauthUserInfoPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from oauthUserInfo slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for oauth_user_info")
	}

	if len(oauthUserInfoAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *OauthUserInfo) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindOauthUserInfo(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *OauthUserInfoSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := OauthUserInfoSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), oauthUserInfoPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `oauth_user_info`.* FROM `oauth_user_info` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, oauthUserInfoPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in OauthUserInfoSlice")
	}

	*o = slice

	return nil
}

// OauthUserInfoExists checks if the OauthUserInfo row exists.
func OauthUserInfoExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `oauth_user_info` where `id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if oauth_user_info exists")
	}

	return exists, nil
}

// Exists checks if the OauthUserInfo row exists.
func (o *OauthUserInfo) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return OauthUserInfoExists(ctx, exec, o.ID)
}
