// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Event               string
	EventTimeUnit       string
	GooseDBVersion      string
	RefreshToken        string
	User                string
	UserEventAnswer     string
	UserEventAnswerUnit string
}{
	Event:               "event",
	EventTimeUnit:       "event_time_unit",
	GooseDBVersion:      "goose_db_version",
	RefreshToken:        "refresh_token",
	User:                "user",
	UserEventAnswer:     "user_event_answer",
	UserEventAnswerUnit: "user_event_answer_unit",
}
