// Code generated by MockGen. DO NOT EDIT.
// Source: ./auth.go

// Package mockmiddleware is a generated GoMock package.
package mockmiddleware

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	echo "github.com/labstack/echo/v4"
)

// MockAuthMiddleware is a mock of AuthMiddleware interface.
type MockAuthMiddleware struct {
	ctrl     *gomock.Controller
	recorder *MockAuthMiddlewareMockRecorder
}

// MockAuthMiddlewareMockRecorder is the mock recorder for MockAuthMiddleware.
type MockAuthMiddlewareMockRecorder struct {
	mock *MockAuthMiddleware
}

// NewMockAuthMiddleware creates a new mock instance.
func NewMockAuthMiddleware(ctrl *gomock.Controller) *MockAuthMiddleware {
	mock := &MockAuthMiddleware{ctrl: ctrl}
	mock.recorder = &MockAuthMiddlewareMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthMiddleware) EXPECT() *MockAuthMiddlewareMockRecorder {
	return m.recorder
}

// CORSHandler mocks base method.
func (m *MockAuthMiddleware) CORSHandler(next echo.HandlerFunc) echo.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CORSHandler", next)
	ret0, _ := ret[0].(echo.HandlerFunc)
	return ret0
}

// CORSHandler indicates an expected call of CORSHandler.
func (mr *MockAuthMiddlewareMockRecorder) CORSHandler(next interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CORSHandler", reflect.TypeOf((*MockAuthMiddleware)(nil).CORSHandler), next)
}

// CSRFHandler mocks base method.
func (m *MockAuthMiddleware) CSRFHandler(next echo.HandlerFunc) echo.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CSRFHandler", next)
	ret0, _ := ret[0].(echo.HandlerFunc)
	return ret0
}

// CSRFHandler indicates an expected call of CSRFHandler.
func (mr *MockAuthMiddlewareMockRecorder) CSRFHandler(next interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CSRFHandler", reflect.TypeOf((*MockAuthMiddleware)(nil).CSRFHandler), next)
}

// SessionHandler mocks base method.
func (m *MockAuthMiddleware) SessionHandler(next echo.HandlerFunc) echo.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SessionHandler", next)
	ret0, _ := ret[0].(echo.HandlerFunc)
	return ret0
}

// SessionHandler indicates an expected call of SessionHandler.
func (mr *MockAuthMiddlewareMockRecorder) SessionHandler(next interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SessionHandler", reflect.TypeOf((*MockAuthMiddleware)(nil).SessionHandler), next)
}
