// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: proto/authorize.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuthorizeClient is the client API for Authorize service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthorizeClient interface {
	GetToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*GetTokenReply, error)
	LinkToken(ctx context.Context, in *LinkTokenRequest, opts ...grpc.CallOption) (*LinkTokenReply, error)
}

type authorizeClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthorizeClient(cc grpc.ClientConnInterface) AuthorizeClient {
	return &authorizeClient{cc}
}

func (c *authorizeClient) GetToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*GetTokenReply, error) {
	out := new(GetTokenReply)
	err := c.cc.Invoke(ctx, "/geekCamp.Authorize/GetToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizeClient) LinkToken(ctx context.Context, in *LinkTokenRequest, opts ...grpc.CallOption) (*LinkTokenReply, error) {
	out := new(LinkTokenReply)
	err := c.cc.Invoke(ctx, "/geekCamp.Authorize/LinkToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthorizeServer is the server API for Authorize service.
// All implementations must embed UnimplementedAuthorizeServer
// for forward compatibility
type AuthorizeServer interface {
	GetToken(context.Context, *GetTokenRequest) (*GetTokenReply, error)
	LinkToken(context.Context, *LinkTokenRequest) (*LinkTokenReply, error)
	mustEmbedUnimplementedAuthorizeServer()
}

// UnimplementedAuthorizeServer must be embedded to have forward compatible implementations.
type UnimplementedAuthorizeServer struct {
}

func (UnimplementedAuthorizeServer) GetToken(context.Context, *GetTokenRequest) (*GetTokenReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetToken not implemented")
}
func (UnimplementedAuthorizeServer) LinkToken(context.Context, *LinkTokenRequest) (*LinkTokenReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LinkToken not implemented")
}
func (UnimplementedAuthorizeServer) mustEmbedUnimplementedAuthorizeServer() {}

// UnsafeAuthorizeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthorizeServer will
// result in compilation errors.
type UnsafeAuthorizeServer interface {
	mustEmbedUnimplementedAuthorizeServer()
}

func RegisterAuthorizeServer(s grpc.ServiceRegistrar, srv AuthorizeServer) {
	s.RegisterService(&Authorize_ServiceDesc, srv)
}

func _Authorize_GetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizeServer).GetToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/geekCamp.Authorize/GetToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizeServer).GetToken(ctx, req.(*GetTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authorize_LinkToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizeServer).LinkToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/geekCamp.Authorize/LinkToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizeServer).LinkToken(ctx, req.(*LinkTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Authorize_ServiceDesc is the grpc.ServiceDesc for Authorize service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Authorize_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "geekCamp.Authorize",
	HandlerType: (*AuthorizeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetToken",
			Handler:    _Authorize_GetToken_Handler,
		},
		{
			MethodName: "LinkToken",
			Handler:    _Authorize_LinkToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/authorize.proto",
}
